version: 2
updates:
# Maintain dependencies for Composer
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 99
  reviewers:
    - fajarafriansh
  assignees:
    - fajarafriansh
  target-branch: "main"
  labels:
    - composer
    - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Maintain dependencies for npm
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 99
  reviewers:
    - fajarafriansh
  assignees:
    - fajarafriansh
  target-branch: "main"
  labels:
    - npm
    - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
